#+title: DROID Tricks

DROID tricks contains a growing list of various patch tricks for the [[https://shop.dermannmitdermaschine.de/pages/droid-universal-cv-processor][DROID Universal CV Processor]].

* Tricks

** Single-button instant mute with clocked un-mute
/Requires blue-3/
Low on buttons and want the =[algoquencer]=' timesynced unmute behavior?

This snippet does the same, but with a single button, and works with =selects= as well.

It requires a longer clock, such as the one from the algoquencer =startofbar=
output for the unmute, and a regular clock for the mute.

The mute state is translated into a inverted state: =_MUTE= is *1* when not
muted to allow you to multiply an output signal with this to mute it.


#+begin_example

# This is a tempo-synced LFO, and will be used to make your unmute LED blink.
[lfo]
    taptempo = _CLOCK
    level = 1
    square = _UNMUTE_SIGNAL


[button]
    select = _LAYER
    states = 2
    button = B1.1
    output = _MUTE_STATE

[switch]
    input1 = _BARCLOCK
    input2 = _CLOCK
    offset = _MUTE_STATE
    output1 = _CLOCK_QUEUE

[queue]
    input = _MUTE_STATE
    clock = _CLOCK_QUEUE
    output1 = _IS_MUTED

[copy]
    input = -1 * _IS_MUTED + 1
    output = _MUTE

[compare]
    input = _MUTE_STATE
    compare = _IS_MUTED
    ifequal = 0
    else = 1
    output = _STATE_TRANSITION

[copy]
    input = -1 * _STATE_TRANSITION + 1
    output = _STATE_CONVERGED

[select]
    input = _UNMUTE_SIGNAL
    select = _STATE_TRANSITION * _LAYER
    output = L1.1

[select]
    input = _MUTE_STATE
    select = _STATE_CONVERGED * _LAYER
    output = L1.1

#+end_example

To use with droid versions older than blue-3, you have to use a mixer to manage
your LED.

** Using mixers to add selects to your LEDs and possibly other things.

This snippet is not very useful from the blue-3 version, but included if someone
is still on an older version and need this functionality.

It allows you to implement =select= for things that do not support it.

If you need =selectat= functionality, you can use a =[compare]= circuit to
convert them into normal =selects=.

#+begin_example
# One mixer per LED
[mixer]
    input1 _LED11_LAYER_1 * _LAYER1
    input2 _LED11_LAYER_2 * _LAYER2
    input3 _LED11_LAYER_3 * _LAYER3
    input4 _LED11_LAYER_4 * _LAYER4
    maximum = L1.1

[mixer]
    input1 _LED12_LAYER_1 * _LAYER1
    input2 _LED12_LAYER_2 * _LAYER2
    input3 _LED12_LAYER_3 * _LAYER3
    input4 _LED12_LAYER_4 * _LAYER4
    maximum = L1.2

#+end_example
